-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:11:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`permiso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`rol` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`permiso_rol` (
  `id` INT NOT NULL,
  `permiso_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permiso_rol_permiso_idx` (`permiso_id` ASC) VISIBLE,
  INDEX `fk_permiso_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_permiso_rol_permiso`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `laravel`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `laravel`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`usuario` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`usuario_rol` (
  `id` INT NOT NULL,
  `estado` TINYINT(1) NULL,
  `rol_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  INDEX `fk_usuario_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_usuario_rol_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `laravel`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `laravel`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`libro` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(30) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `cantidad` TINYINT(2) NOT NULL,
  `editorial` VARCHAR(50) NULL,
  `foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`libro_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`libro_prestamo` (
  `id` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `prestado_a` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fecha_devolucion` DATE NULL,
  `usuario_id` INT NOT NULL,
  `libro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libro_prestamo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_libro_prestamo_libro1_idx` (`libro_id` ASC) VISIBLE,
  CONSTRAINT `fk_libro_prestamo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `laravel`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_prestamo_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `laravel`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
